name: Build Docker images on Cloud Build

on:
  workflow_dispatch:

  push:
    branches:
      - 'master'
      - 'new-architecture-crmint-3.0'
    paths-ignore:
      - 'README.md'
jobs:
  build-controller-image:
    runs-on: ubuntu-18.04
    # Add "id-token" with the intended permissions.
    permissions:
      contents: read
      id-token: write
    steps:
      # Clone repository code
      - uses: actions/checkout@v3
      # Authenticate to GCP
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.CLOUD_BUILD_RUNNER_SA }}'
      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      # Build and push image to Google Container Registry
      - name: Build
        working-directory: backend
        run: |-
          gcloud builds submit \
            --quiet \
            --config controller_cloudbuild.yaml \
            --substitutions _DOCKERFILE=controller.Dockerfile,_IMAGE_NAME=europe-docker.pkg.dev/instant-bqml-demo-environment/crmint/controller
