name: terraform-plan

# NOTE: won't have access to secrets on PR from forks.

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - 'master'

jobs:
  run-terraform:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        use_vpc: ['false', 'true']
    defaults:
      run:
        working-directory: terraform
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Save artifacts
        run: |
          mkdir -p ./pr/terraform
          echo ${{ steps.init.outcome }} > ./pr/terraform/init_outcome
          echo ${{ steps.validate.outcome }} > ./pr/terraform/validate_outcome
          echo ${{ steps.validate.outputs.stdout }} > ./pr/terraform/validate_output

      - uses: actions/upload-artifact@v3
        with:
          name: pr
          path: pr/
