name: testing-backend
on:
  workflow_dispatch:

  push:
    paths-ignore:
      - 'README.md'
jobs:
  run-backend-tests:
    runs-on: ubuntu-18.04
    steps:
      # Checkout repository code
      - uses: actions/checkout@v2
      # Configure python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      # Setup the CRMint test environment
      - name: Install dependencies
        working-directory: backend
        run: |
          pip install -r requirements-controller.txt
          pip install -r requirements-jobs.txt
          pip install -r tests/requirements.txt
      # Run the tests
      - name: Run the tests
        working-directory: backend
        run: pytest --cov=. --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          working-directory: backend
          fail_ci_if_error: true
          flags: backend
