name: testing-backend
on:
  pull_request:
    branches:
      - master
      - dev
jobs:
  run-backend-tests:
    runs-on: ubuntu-18.04
    steps:
      # Checkout repository code
      - uses: actions/checkout@v2
      # Configure python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      # Setup the CRMint test environment
      - name: Install dependencies
        run: |
          pip install -r backend/requirements-controller.txt
          pip install -r backend/requirements-jobs.txt
          pip install -r backend/tests/requirements.txt
      # Run the tests
      - run: cd backend && pytest --cov=. --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          flags: backend
